### ISSUE TITLE
New release with enhanced Sentry configuration

### ISSUE THREAD

**Issue by pkajaba** [selinon/selinon#121]
I would like to ask for new release, which includes code base around Sentry configuration through environmental variables.

Thank you!

**Comment by fridex** [comment]
A new version from the current master is available on [PyPI](https://pypi.python.org/pypi?:action=display&name=selinon&version=1.0.0rc4). It's still rc4, I would like to have #57 fixed before version 1.0.0. 

Thanks for your interest!
