### ISSUE TITLE
Guidance for integrating Selinon as a library

### ISSUE THREAD

**Issue by kavink** [selinon/selinon#125]
This is a great project and reading code, This looks like doing almost everything I want to do. Because for my project I already have a DSL in yaml which user can specify flows and while trying to figure out if there was better workflow engine for Celery I found this. Which is great!. I can totally switch to using Selinon yaml DSL.

But I am still struggling trying to figure out how I can integrate it with my project, As its going to be a REST service(Flask/Redis/Postgres/Celery/Flower), I am trying to figure out the following 

- how I can allow creating/editing/deleting of flows from API
- Triggering flows with different values
- Monitor status of the flow i.e. which stage is running, status of stage/flow, Result from the single stage or entire flow
- Ability to rerun failed stages or force rerun of flows.
- Possibly how to extend to send notifications via email about success/failure.

Please can you point me in right direction, either which code blocks to use or best if you can extend the demo to show all the cool features which I see in Readme and code.

**Comment by kavink** [comment]
@fridex Any thoughts ?

**Comment by fridex** [comment]
> This is a great project and reading code, This looks like doing almost everything I want to do. Because for my project I already have a DSL in yaml which user can specify flows and while trying to figure out if there was better workflow engine for Celery I found this. Which is great!. I can totally switch to using Selinon yaml DSL.

> But I am still struggling trying to figure out how I can integrate it with my project, As its going to be a REST service(Flask/Redis/Postgres/Celery/Flower), I am trying to figure out the following 

> - how I can allow creating/editing/deleting of flows from API

YAML config files are cluster configuration. If you want to create/edit/delete flow or do anything in the YAML configuration file, you need to do redeployment and apply [migrations](http://selinon.readthedocs.io/en/latest/migrations.html).

> - Triggering flows with different values

See [docs](http://selinon.readthedocs.io/en/latest/start.html#running-a-flow) - there is an argument `node_args` for [run_flow](http://selinon.readthedocs.io/en/latest/selinon/doc/selinon.run.html#selinon.run.run_flow) function that starts the requested flow with different arguments.

> - Monitor status of the flow i.e. which stage is running, status of stage/flow, Result from the single stage or entire flow

You can use built-in [tracing mechanism](http://selinon.readthedocs.io/en/latest/trace.html). For results, you need to check databases/storages used for individual tasks as configured.

> - Ability to rerun failed stages or force rerun of flows.

Please check my comment [here](https://github.com/selinon/demo/issues/11#issuecomment-379586189).

> - Possibly how to extend to send notifications via email about success/failure.

Use already existing [sentry support](http://selinon.readthedocs.io/en/latest/trace.html#sentry-integration) or you can code your tasks as desired. Please also check task (and flow) [failures](http://selinon.readthedocs.io/en/latest/tasks.html#task-failures).

> Please can you point me in right direction, either which code blocks to use or best if you can extend the demo to show all the cool features which I see in Readme and code.

Selinon is now my free time project so time spent on features is limited. But definitely on my TODO list.

**Comment by fridex** [comment]
This issue is getting stalled. Closing it - feel free to reopen if there you need more comments.
