### ISSUE TITLE
Comment in code thoughts ?

### ISSUE THREAD

**Issue by kavink** [selinon/selinon#126]
Thanks for the great work, I spend some part of today going through the code, wondering if you think its work commenting your thoughts on what each file/class/function does i.e. how does it all tie together,  I do get it 😄 Comments get old and normally comments lie ... But for first time reader it , would help me understand from creators pov why the code is designed the way it is, So if needed I can extend/modify it for my use cases.

e.g. I started from dispatcher, then went to system_state and executors , But im still trying to figure where exactly do you poll and wait or subscribe to async tasks  triggered.

Because celery docs says a task should not wait on other tasks to avoid deadlocks etc. So wondering how your code implemented the main dispatchers, such that it traverses the DAG and triggers stages in order or in parallel or join etc.

**Comment by fridex** [comment]
Check docs - there is a separate section for selinon [internals](http://selinon.readthedocs.io/en/latest/internals.html). I would suggest to first understand how Celery tasks work, but your starting points were correct - Dispatcher and SelinonTask are the first classes to start with. SystemState is the core part for the whole scheduling computing mechanism.

**Comment by fridex** [comment]
> I would suggest to first understand how Celery tasks work

There are basically used [async_apply](http://docs.celeryproject.org/en/latest/reference/celery.app.task.html#celery.app.task.Task.apply_async) and [retry](http://docs.celeryproject.org/en/latest/reference/celery.app.task.html#celery.app.task.Task.retry) methods. Also check what are workers and what is a message queue. That should be all on Celery side. Then check the internals section on how there is performed sampling using retries.

**Comment by fridex** [comment]
This issue is getting stalled. Closing it - feel free to reopen if there you need more comments.
