### ISSUE TITLE
how can I get the progress and state of flow?

### ISSUE THREAD

**Issue by lvscup** [selinon/selinon#141]
hello，
Question 1: when I run a flow, it contains 4 tasks A/B/C/D，A->B->C->D，if C costs a long time, how can I get the percentage of progress in real-time? Is there some methods supporting this?
Question 2: as the description of Question 1，how can I get the state of flow? In other issues, somebody mentions to use [Trace flow actions](https://selinon.readthedocs.io/en/latest/trace.html), I use celery.AsyncResult to get the state. Is there a better way?

**Comment by lvscup** [comment]
Ok, thanks. I will try it with tracing.

**Comment by fridex** [comment]
> Ok, thanks. I will try it with tracing.

Fingers crossed. Feel free to reach out again in case of any questions.
