### ISSUE TITLE
Using Environment variables in storage? 

### ISSUE THREAD

**Issue by sniranjan** [selinon/selinon#144]
## Issue description:
Can I use environment variables in storage? 
https://github.com/selinon/selinon/blob/b19a682bca006aa317c936d00aa8886c479fb763/docs.source/yaml.rst#storages 
For example in connection string for username/password?

### Steps to reproduce:
Run a flow with storage where connection string has environment variables like the one below
  storages:
    - name: Redis
      import: selinon.storages.redis
      configuration:
        host: {REDIS_HOST}
        port: {REDIS_PORT}
        password: {REDIS_PASSWORD}
        db: 1
        charset: 'utf-8

### Expected behavior:
Expected Selinon to expand the environment variables

### Actual behavior:
Flow stops after the first task. Evironment variable expansion not happening.

### Links to logs:

A link to logs posted on http://pastebin.com/ (or any other publicly reachable service).

### Selinon & Celery version:

Running `selinon-cli version` gave me:
latest

- [ X] I have tried the latest master but the issue still pesists:
  `pip3 install --force-reinstall git+https://github.com/selinon/selinon@master`

**Comment by fridex** [comment]
It is not possible with the current implementation. I've opened #145 as an example implementation. Please let me know if that works for you. Other adapters will need this adjustment as well (as state it in the docs).

**Comment by sniranjan** [comment]
@fridex  This will work for me. Thank you so much!

**Comment by fridex** [comment]
Happy to help! Enjoy!
