### ISSUE TITLE
how to call task flows define in yaml config file from remote server?

### ISSUE THREAD

**Issue by dusteye** [selinon/selinon#36]
## Issue description:
no docment describe how to call flows define in yaml config file

### Links to logs:

A link to logs posted on http://pastebin.com/ (or any other publicly reachable service).

### Selinon & Selinonlib & Celery version:

Running `selinonlib-cli version` gave me:

- [ ] I have tried the latest master but the issue still pesists:
  `pip3 install --force-reinstall git+https://github.com/selinon/selinonlib@master`
  `pip3 install --force-reinstall git+https://github.com/selinon/selinon@master`

**Comment by fridex** [comment]
Yes, you are right. I will update the docs.

To run some flow (let's say "myFlow"), just call [`run_flow`](http://selinon.readthedocs.io/en/latest/selinon/doc/selinon.utils.html#selinon.utils.run_flow) function and supply arguments to the flow:
```python
from selinon import run_flow

run_flow('myFlow', node_args={'foo': 'bar'})
```

If you would like to run only [some tasks in a flow](http://selinon.readthedocs.io/en/latest/selective.html), use the [`run_flow_selective`](http://selinon.readthedocs.io/en/latest/selinon/doc/selinon.utils.html#selinon.utils.run_flow_selective) function:
```python
from selinon import run_flow

run_flow_selective('myFlow', ['Task1', 'Task2'], node_args={'foo': 'bar'})
```

If there is anything unclear, feel free to ask.

**Comment by dusteye** [comment]
I have another quetion: how to fetch the flow result? I found that run_flow result is a celery asyncResult, but use get method celery asyncResult, it's blocked and can not return.

**Comment by fridex** [comment]
> I have another quetion: how to fetch the flow result? I found that run_flow result is a celery asyncResult, but use get method celery asyncResult, it's blocked and can not return.

The [`run_flow`](http://selinon.readthedocs.io/en/latest/selinon/doc/selinon.utils.html#selinon.utils.run_flow) function returns async result for dispatcher that is handling the requested flow. Results are stored on task level based [on assigned adapters](https://selinon.readthedocs.io/en/latest/storage.html). There is no mechanism  to get results of all tasks in the flow as they can use different storages and the structure of stored results in storages/adapters is left on users.

You can run a flow with arguments based on which you can query storage/database in the adapter implementation - you can request the given [storage adapter from pool](http://selinon.readthedocs.io/en/latest/storage.html#database-connection-pool) and call querying methods to get results. You need to know at least task name (and possibly storage adapter) that results you want to get.

It might sound difficult, but it is not. I can provide you some example if you want.

**Comment by fridex** [comment]
OK, I will close this. @dusteye feel free to reopen if more input is needed.
