### ISSUE TITLE
please include a simple example in the readme 

### ISSUE THREAD

**Issue by TomasTomecek** [selinon/selinon#8]
For me, the first impression is everything. Right now, the readme doesn't engage me in any way. Including a simple example (ideally with a diagram) would definitely do the trick.

**Comment by fridex** [comment]
Thank you Tomas for the suggestion. I've included a simple example in README.md. I will close this, feel free to reopen this issue if there is anything wrong (or the example is not clear). I need to improve documentation as well, but that's another story.

**Comment by TomasTomecek** [comment]
well done!
