### ISSUE TITLE
1.0.0rc1 breaks flow definitions

### ISSUE THREAD

**Issue by oafx** [selinon/selinon#94]
Hi there, small heads up and incomplete issue description due to lack of time (sorry for that), **the issue doesn't seem to persist in selinon@master**

If additional information is required i'd be glad to help.

## Issue description:

The CI/CD-Pipelines of our Selinon based project began to fail with a `ConfigurationError` after 1.0.0rc1 was released to pypi (we didn't use a fixed version in requirements.txt). 

### Steps to reproduce:
Update project dependencies/selinon and selinonlib from 0.1.0rc9 to 1.0.0rc1 via pip/pypi

### Expected behavior:
Well _I did expect_ that my flow definitions would still work. 

### Actual behavior:
Exits with `ConfigurationError` 

### Links to logs:

A link to logs posted on http://pastebin.com/ (or any other publicly reachable service).

```
16: [23:04:47] selinonlib.system from_files:1180: Parsing 'myflows.yaml'
16: [23:04:47] selinonlib.system _setup_flows:1148: Failed to parse flow definition for flow 'flow1', in file 'myflows.yaml'
16: [23:04:47] selinonlib-cli <module>:448: No flow edges provided in flow 'myflows.yaml'
Traceback (most recent call last):
  File "/usr/local/bin/selinonlib-cli", line 446, in <module>
    sys.exit(Command.main())
  File "/usr/local/bin/selinonlib-cli", line 441, in main
    return command(args)
  File "/usr/local/bin/selinonlib-cli", line 225, in plot
    system = System.from_files(args.nodes_definition, args.flow_definitions)
  File "/usr/local/lib/python3.6/site-packages/selinonlib/system.py", line 1187, in from_files
    cls._setup_flows(system, content, flow_file)
  File "/usr/local/lib/python3.6/site-packages/selinonlib/system.py", line 1144, in _setup_flows
    flow.parse_definition(flow_def, system)
  File "/usr/local/lib/python3.6/site-packages/selinonlib/flow.py", line 120, in parse_definition
    raise ConfigurationError("No flow edges provided in flow %r" % self.name)
selinonlib.errors.ConfigurationError: No flow edges provided in flow 'flow1'
```

### Are you able to reproduce the issue with `selinon-cli execute`?

not tested.

### Selinon & Celery version:

_can't tell right now but should be 1.0.0rc1_

Running `selinon-cli version` gave me:

- [ ] I have tried the latest master but the issue still pesists:
  `pip3 install --force-reinstall git+https://github.com/selinon/selinon@master`
**THIS IS NOT THE CASE, ISSUE DOESN'T PERSIST IN SELINON@MASTER**

### Links to YAML config files:

myflows.yaml:
```
#[...]
flow-definitions:
  - name: 'flow1'
    edges:
      - from:
        to: 'task1'
      - from: 'task1'
        to: 'flow2'
      - from: 'flow2'
        to: 'task2'
#[...]
``` 
### Links to task implementations:

_not provided_

**Comment by fridex** [comment]
I've submitted a PR to release v1.0.0rc2 from the current master in #95 - it will be published soon on PyPI. There were large changes since then (mainly merging selinon and selinonlib), please let me know if the issue was fixed or if it persists.

Thanks for the report!

**Comment by fridex** [comment]
A new release is available at PyPI.

**Comment by oafx** [comment]
Yep that fixed it, thanks a lot!
